[window]
option_as_alt = "Both"

[font]
size = 30.0

[font.bold]
family = "Ricty Diminished"
style = "Bold"

[font.bold_italic]
family = "Ricty Diminished"
style = "Bold Oblique"

[font.italic]
family = "Ricty Diminished"
style = "Oblique"

[font.normal]
family = "MyricaMonospace Nerd Font" # https://github.com/mkasa/myrica-nerdfonts

[[keyboard.bindings]]
chars = '\'
key = "_"

[[keyboard.bindings]]
chars = "\u001C"
key = "_"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"
